#!/bin/bash

set -o nounset
set -o errexit
set -o pipefail

directory=$(cd -P "$(dirname "${BASH_SOURCE[0]}")" && pwd)
interval=${1:-"60"}
iface=${2:?}

rx_bytes=$(cat /sys/class/net/${iface}/statistics/rx_bytes)
tx_bytes=$(cat /sys/class/net/${iface}/statistics/tx_bytes)

sleep ${interval:?}

rx_bytes=$(($(cat /sys/class/net/${iface}/statistics/rx_bytes)-rx_bytes))
tx_bytes=$(($(cat /sys/class/net/${iface}/statistics/tx_bytes)-tx_bytes))

echo "$(numfmt --to iec --format '%4.1f' $(bc -q <<<"scale=1; ${rx_bytes} / ${interval}"))B/s" | tee "${directory}/.rxspeed.txt"
echo "$(numfmt --to iec --format '%4.1f' $(bc -q <<<"scale=1; ${tx_bytes} / ${interval}"))B/s" | tee "${directory}/.txspeed.txt"
